import 'guide_service.dart';

/// Offline fallbacks for Umrah & Hajj — keep in sync with
/// supabase/migrations/20260825140000_umrah_hajj_guide_refresh.sql
abstract final class PilgrimageGuideFallbacks {
  static const umrah = <GuideStep>[
    GuideStep(
      title: 'Before Assuming Ihram',
      body: '',
      subtitle: 'Ghusl · Niyyah · Settle your affairs',
      description: 'Congratulations, you are a guest of Allah (swt). Prepare yourself in the best possible way, as you are about to visit the most sacred building in the world – the first Masjid built for the worship of Allah.\n\nYou may need to do Ghusl (bath) or Wudu (ablution) before wearing Ihram. Men can also apply Attar (perfume) to their hair or beard at this stage (if not yet in Ihram).\n\n**Note:** You can put on your Ihram garment beforehand (physically wearing it), but you only enter the "state of Ihram" when you make the intention at the Miqat point.\n\n**Once you enter the State of Ihram, you must not:**\n\n- Cut or pluck your hair\n- Use perfume or scented items\n- Wear any stitched clothes (men only)\n- Cover your head (men only)\n- Trim your nails\n- Hunt animals\n- Smoke or take drugs\n- Engage in quarrels or fights',
      arabic: 'الإحرام',
      sortOrder: 1,
    ),
    GuideStep(
      title: 'Change into Your Ihram',
      body: '',
      subtitle: 'Men: two white cloths · Women: modest dress',
      description: '**Men**\n\nWear two white sheets (Ihram): one wrapped around the waist and the other draped over the upper body. Slippers should be worn that do not cover the ankles, but hats, turbans, or any head coverings are not permitted.\n\n**Women**\n\nMay wear their usual modest clothing, but must avoid wearing gloves or covering their face (unless in front of non-Mahram men if they usually wear niqab).\n\n**You must:**\n\n- Ensure you change into your Ihram attire before crossing the Miqat\n- If traveling by plane to Arabia, enter into Ihram before departure or during a stopover\n- If you can, try to combine wearing the Ihram with an obligatory or optional prayer',
      arabic: 'لباس الإحرام',
      sortOrder: 2,
    ),
    GuideStep(
      title: 'Make the Intention for Umrah',
      body: '',
      subtitle: 'Miqat is 20–30 min before landing',
      description: 'For those flying from abroad, the Miqat point is usually passed about 20–30 minutes before landing. They may announce this, or you can track it yourself. At this point, make the intention for Umrah.\n\n> لَبَّيْكَ اللَّهُمَّ عُمْرَةً\n>\n> Labbayk Allahumma Umrah.\n>\n> Here I am O Allah making Umrah.\n\n**Optional Du\'a:**\n\n> اللَّهُمَّ هَذِهِ عُمْرَةٌ لَا رِيَاءَ فِيهَا وَلَا سُمْعَةَ\n>\n> Allahumma hādhihi \'Umrah, lā riyā\'a feehā wa lā sum\'ah.\n>\n> O Allah this is an Umrah, there is no showing off in it nor seeking reputation.',
      arabic: 'النية عند الميقات',
      sortOrder: 3,
    ),
    GuideStep(
      title: 'Recite the Talbiyah',
      body: '',
      subtitle: 'Men: loud · Women: softly · Until Tawaf',
      description: 'Men should recite this in a loud voice, while women should recite it softly. Continue until you reach Masjid al-Haram in Makkah.\n\n> لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لَا شَرِيكَ لَكَ\n>\n> Labbayka Allahumma labbayka, labbayka la sharika laka labbayka, inna l-hamda wa n-ni\'mata laka w-al-mulk, la sharika lak.\n>\n> At your service, Allah, at your service. You have no partner; at your service. Truly all praise, favor and sovereignty are Yours; You have no partner.\n\n**Hadith:** "When any pilgrim utters Talbiyah, everything on his right and left, whether it be stones, trees, or clay, joins him in his statement." [Sahih Muslim 1184]',
      arabic: 'التلبية',
      sortOrder: 4,
    ),
    GuideStep(
      title: 'Entering Masjid Al-Haram',
      body: '',
      subtitle: 'Enter with right foot · Recite du\'a',
      description: 'Enter the Masjid Al-Haram (the Sacred Mosque) with your **right foot first** and recite:\n\n> اللَّهُمَّ صَلِّ عَلَى مُحَمَّدٍ وَسَلِّمْ اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ\n>\n> Allāhumma ṣalli \'alā Muḥammadin wa sallim. Allāhumma iftaḥ-lee abwāba raḥmatika.\n>\n> O Allah, send peace upon Muhammad. O Allah open the doors of Your Mercy for me.\n\nAvoid distractions from devices and the busy crowds. Rather, focus on your Lord and the significance of your journey.',
      arabic: 'دخول المسجد الحرام',
      sortOrder: 5,
    ),
    GuideStep(
      title: 'Performing Tawaf',
      body: '',
      subtitle: 'State of Wudu · Men: Iztiba\'',
      description: 'Make sure you are in a state of Wudu and walk towards the Mataf area (i.e. where people are walking around the Ka\'bah).\n\n**Men — Iztiba\'**\n\nUncover your right shoulder (known as Iztiba\') before starting Tawaf.',
      arabic: 'التهيؤ للطواف',
      sortOrder: 6,
    ),
    GuideStep(
      title: 'Start Tawaf',
      body: '',
      subtitle: 'Black Stone · Bismillah Allahu Akbar · 7 circuits',
      description: 'Start at Al-Hajr Al-Aswad (the Black Stone). If you look to your right (away from the Ka\'bah) you will see green-fluorescent light. This is your starting point.\n\n> بِسْمِ اللهِ اللهُ أَكْبَرُ\n>\n> Bismillah Allahu Akbar\n>\n> Allah is the Greatest.\n\nTry touching the Black Stone (or kissing it) — if you cannot, make a sign with your right hand towards it. You will complete **7 tawafs (circuits)**. On the first three circuits, men should perform Raml (walking briskly).\n\nYou can make any supplication, say words of Dhikr or recite Qur\'an — it is your choice. You are in front of Allah, the Creator of the Universe.',
      arabic: 'بدء الطواف',
      sortOrder: 7,
    ),
    GuideStep(
      title: 'Yemeni Corner',
      body: '',
      subtitle: 'Recite Rabbana ātina each time you pass',
      description: 'Each time you pass the Yemeni corner of the Ka\'bah (the corner before the corner of the Black Stone), recite:\n\n> رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ\n>\n> Rabbana ātina fi d-dunyā ḥasanatan wa fi l-ākhirati ḥasanatan wa qinā \'adhāba n-nār.\n>\n> O our Lord, grant us the good of this world, the good of the Hereafter, and save us from the punishment of the fire.',
      arabic: 'الركن اليماني',
      sortOrder: 8,
    ),
    GuideStep(
      title: 'Complete 7 Circuits',
      body: '',
      subtitle: 'Count from first complete circuit',
      description: '**Note:** Ensure you complete 7 circuits counting the first one after you had completed the tawaf, not counting it from the beginning.',
      arabic: 'إتمام الطواف',
      sortOrder: 9,
    ),
    GuideStep(
      title: 'After Tawaf',
      body: '',
      subtitle: 'Maqam Ibrahim · 2 Rak\'ahs',
      description: 'After performing Tawaf, proceed to the Maqam Ibrahim and recite the following verse (men should cover both shoulders at this point):\n\n> وَاتَّخِذُوا مِنْ مَقَامِ إِبْرَاهِيمَ مُصَلًّى\n>\n> Wattakhidhoo min Maqaami Ibraheema musalla.\n>\n> And take the Maqam Ibrahim as a place of Salah.\n\nPray **2 Rak\'ahs** behind Maqam Ibrahim if possible, otherwise as close as possible. Recite **Surah Al-Kafirun** in the first Rak\'ah and **Surah Al-Ikhlas** in the second.',
      arabic: 'بعد الطواف',
      sortOrder: 10,
    ),
    GuideStep(
      title: 'Drink Zamzam',
      body: '',
      subtitle: 'Make du\'a · Pour over your head',
      description: 'Then go to the Zamzam taps and drink from it and pour some of the water over your head. Make plenty of supplication for good when drinking Zamzam.\n\nThe Prophet ﷺ is reported to have said: "It [Zamzam] is blessed, it is nourishment that satisfies and a cure for sickness." (Sahih Muslim)',
      arabic: 'شرب ماء زمزم',
      sortOrder: 11,
    ),
    GuideStep(
      title: 'Make Your Way to Mount Safa',
      body: '',
      subtitle: 'Recite the verse of Safa & Marwah',
      description: 'As you ascend towards Safa, recite:\n\n> إِنَّ الصَّفَا وَالْمَرْوَةَ مِنْ شَعَائِرِ اللهِ فَمَنْ حَجَّ الْبَيْتَ أَوِ اعْتَمَرَ فَلَا جُنَاحَ عَلَيْهِ أَنْ يَطَّوَّفَ بِهِمَا وَمَنْ تَطَوَّعَ خَيْرًا فَإِنَّ اللهَ شَاكِرٌ عَلِيمٌ — نَبْدَأُ بِمَا بَدَأَ اللهُ بِهِ\n>\n> Innas-Safaa wal-Marwata min sha\'aa\'irillah… Nabda\'u bimaa bada\'Allahu bihi.\n>\n> Verily Safa and Marwah are from the signs of Allah… I begin with what Allah begins with.\n\nProceed to climb Mount Safa, face the Ka\'bah if possible, and make any personal supplication or du\'a you wish. You can repeat this du\'a each time you ascend Safa and Marwah.',
      arabic: 'الصعود إلى الصفا',
      sortOrder: 12,
    ),
    GuideStep(
      title: 'Upon Reaching Safa',
      body: '',
      subtitle: 'Face Ka\'bah · Allahu Akbar · Lā ilāha illAllāh',
      description: 'Face the direction of the Ka\'bah and say:\n\n> اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ، اللَّهُ أَكْبَرُ\n>\n> Allāhu akbar, Allāhu akbar, Allāhu akbar.\n>\n> Allah is the Greatest, Allah is the Greatest, Allah is the Greatest.\n\nThen:\n\n> لَا إِلٰهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ، يُحْيِي وَيُمِيتُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ\n>\n> Lā ilāha illAllāh wahdahu lā shareekalah, lahul mulk, wa lahul-hamd, yuhyee wa yumeet—wa huwa \'ala kulli shay\'in qadeer. Lā ilāha illAllāh wahdahu lā shareekalah, anjaza wa\'dahu, wa nasara \'abdahu, wa hazamal ahzāba wahdah.\n>\n> There is none worthy of worship except Allāh alone, without partner. To Him belongs all sovereignty and all praise. He alone gives life and death—and He is All-Powerful over everything. There is none worthy of worship except Allāh alone, without partner. He has fulfilled His promise, aided His servant, He alone has defeated the confederates.',
      arabic: 'عند الصفا',
      sortOrder: 13,
    ),
    GuideStep(
      title: 'Between the Green Lights',
      body: '',
      subtitle: 'Men: run · Women: walk normally',
      description: 'Upon encountering the green lights between the two hills, **men only** should run from one green light to the next. Women should continue walking normally. This symbolizes the striving of Hajar (may Allah be pleased with her).\n\n**Tip:** Maintain your dhikr or du\'a during this portion as well, remembering the story of Prophet Ibrahim\'s wife Hajar and her faith in Allah\'s plan.',
      arabic: 'بين العلمين الأخضرين',
      sortOrder: 14,
    ),
    GuideStep(
      title: 'Shaving or Cutting Hair',
      body: '',
      subtitle: 'Fard · Men: shave or trim · Women: one inch',
      description: 'Completing Umrah requires ending the Ihram state by removing your hair.\n\n**For Men**\n\nShaving the head is highly recommended (Sunnah), but trimming is also allowed. The Prophet ﷺ prayed for forgiveness three times for those who shave their heads, highlighting its greater reward. Shaving is considered more virtuous as an act of humility before Allah, symbolizing a fresh start and spiritual renewal.\n\n**For Women**\n\nTrim a small portion (approximately one inch) of hair from the end.\n\nWith this, the Umrah is complete, and you may exit the state of Ihram and resume everyday activities.',
      arabic: 'الحلق أو التقصير',
      sortOrder: 15,
    ),
    GuideStep(
      title: 'Your Umrah is Complete – Mubarak!',
      body: '',
      subtitle: 'May Allah accept your Umrah (Ameen)',
      description: '**Taqabbal Allahu minna wa minkum**\n\nMay Allah accept your Umrah and may He answer all your Duas (ameen). Please also pray for us at the Qur\'an Project – that Allah accepts our work and blesses us with Jannah tul Firdaus without reckoning (ameen).',
      arabic: 'تقبَّل الله عمرتك',
      sortOrder: 16,
    ),
  ];

  static const hajj = <GuideStep>[
    GuideStep(
      title: 'Before Assuming Ihram',
      body: '',
      subtitle: 'Ghusl · Niyyah · Settle your affairs',
      description: 'You are a guest of Allah (swt) for Hajj — the fifth pillar of Islam. Prepare yourself in the best possible way. Perform Ghusl, clip your nails and remove excess body hair before leaving home.\n\n- Make sincere intention (niyyah) to perform Hajj solely for Allah\'s pleasure\n- Settle all debts and resolve any outstanding disputes\n- Seek forgiveness from those you may have wronged\n- Write a will before traveling\n- Learn the rites of Hajj before departing',
      arabic: 'الإحرام',
      sortOrder: 1,
    ),
    GuideStep(
      title: 'Change into Your Ihram',
      body: '',
      subtitle: 'Men: two white cloths · Women: modest dress',
      description: '**Men**\n\nTwo white unstitched sheets — izar (lower) and rida (upper). No head coverings, no stitched garments. Slippers must not cover the ankle.\n\n**Women**\n\nUsual modest clothing. Must not wear gloves or cover the face (except in front of non-Mahram men if they normally wear niqab).\n\nChange before crossing the Miqat. If flying, change before departure or during a stopover.',
      arabic: 'لباس الإحرام',
      sortOrder: 2,
    ),
    GuideStep(
      title: 'Make Intention & Recite Talbiyah',
      body: '',
      subtitle: 'At the Miqat · Recite loudly until Day of Eid',
      description: 'At the Miqat, make your intention for the type of Hajj you are performing (most common: Hajj al-Tamattu), then recite the Talbiyah:\n\n> لَبَّيْكَ اللَّهُمَّ لَبَّيْكَ، لَبَّيْكَ لَا شَرِيكَ لَكَ لَبَّيْكَ، إِنَّ الْحَمْدَ وَالنِّعْمَةَ لَكَ وَالْمُلْكَ، لَا شَرِيكَ لَكَ\n>\n> Labbayka Allahumma labbayka…\n>\n> At your service, Allah — all praise, favour and sovereignty are Yours.\n\nContinue reciting Talbiyah frequently until you stone Jamarat al-Aqabah on the 10th of Dhul Hijjah. (Sahih Muslim 1184)',
      arabic: 'النية والتلبية',
      sortOrder: 3,
    ),
    GuideStep(
      title: '8th Dhul Hijjah — Arrive in Mina',
      body: '',
      subtitle: 'Spend the night in Mina · 5 prayers',
      description: 'On the 8th of Dhul Hijjah (Yawm al-Tarwiyah), make your way to Mina and spend the day and night there.\n\n- Pray Dhuhr, Asr, Maghrib, Isha and Fajr in Mina — shortening prayers to 2 rak\'ahs (Qasr)\n- Spend the night in your tent. Reflect, make du\'a, and prepare your heart for the Day of Arafat.',
      arabic: 'يوم التروية — منى',
      sortOrder: 4,
    ),
    GuideStep(
      title: '9th Dhul Hijjah — Stand at Arafat',
      body: '',
      subtitle: 'The pinnacle of Hajj · Du\'a from Dhuhr to sunset',
      description: '> "Hajj is Arafat." (Abu Dawud 1949)\n>\n> — The Prophet Muhammad ﷺ\n\nStand at Arafat from after Dhuhr until sunset. This is the most important act of Hajj — make abundant du\'a, dhikr, and seek Allah\'s forgiveness.\n\nThe best du\'a is: **Lā ilāha illallāhu wahdahu lā sharīka lah, lahul-mulku wa lahul-hamdu wa huwa \'alā kulli shay\'in qadīr.**',
      arabic: 'يوم عرفة',
      sortOrder: 5,
    ),
    GuideStep(
      title: 'Night in Muzdalifah',
      body: '',
      subtitle: 'Collect pebbles · Pray Maghrib & Isha',
      description: 'After sunset on the 9th, depart Arafat for Muzdalifah. Combine and shorten Maghrib (3) and Isha (2) prayers upon arrival.\n\n- Collect 49 or 70 small pebbles (the size of a chickpea) for the stoning of Jamarat.\n- Spend the night under the open sky at Muzdalifah — this is Sunnah.\n- Pray Fajr here. Depart for Mina after Fajr (or in the last portion of the night for the elderly/weak).',
      arabic: 'المزدلفة',
      sortOrder: 6,
    ),
    GuideStep(
      title: '10th Dhul Hijjah — Rami al-Jamarat',
      body: '',
      subtitle: 'Stone Jamarat al-Aqabah · 7 pebbles',
      description: 'Return to Mina and stone Jamarat al-Aqabah (the large pillar) with 7 pebbles. Say **Bismillah, Allahu Akbar** with each throw.\n\n> بِسْمِ اللهِ اللهُ أَكْبَرُ\n>\n> Recite with each of the 7 pebbles\n\nAfter stoning, the Talbiyah stops. Next: sacrifice, shave/cut hair, and change out of Ihram.',
      arabic: 'رمي الجمرات',
      sortOrder: 7,
    ),
    GuideStep(
      title: 'Sacrifice & Exit Ihram',
      body: '',
      subtitle: 'Qurbani · Shave or cut hair · Change clothes',
      description: 'On the Day of Eid (10th Dhul Hijjah), after stoning Jamarat al-Aqabah:\n\n1. **Sacrifice (Hady)** — Offer your sacrificial animal (or arrange through an authorised agent).\n2. **Shave or cut hair (Halq/Taqsir)** — Men should ideally shave the head completely. Women cut a fingertip\'s length from their hair.\n3. **Change out of Ihram** — After shaving, you may change into regular clothing. Most restrictions of Ihram are now lifted.',
      arabic: 'الهدي والتحلل',
      sortOrder: 8,
    ),
    GuideStep(
      title: 'Tawaf al-Ifadah & Sa\'i',
      body: '',
      subtitle: '7 circuits of the Kaaba · 7 rounds of Sa\'i',
      description: 'Return to Makkah and perform Tawaf al-Ifadah — 7 circuits around the Kaaba. This is a pillar of Hajj; without it, Hajj is incomplete.\n\n**After Tawaf**\n\nPray 2 rak\'ahs behind Maqam Ibrahim, drink Zamzam water, then perform Sa\'i — walking 7 times between Safa and Marwah.\n\nAfter completing Sa\'i, all restrictions of Ihram are fully lifted — Hajj is essentially complete.',
      arabic: 'طواف الإفاضة والسعي',
      sortOrder: 9,
    ),
    GuideStep(
      title: 'Days of Tashreeq & Farewell Tawaf',
      body: '',
      subtitle: '11th–13th: stone all 3 Jamarat · Tawaf al-Wida',
      description: '**Days of Tashreeq (11th–13th Dhul Hijjah)**\n\nStone all three Jamarat (small, medium, large) — 7 pebbles each — after midday on each day. You may depart on the 12th if you leave before sunset (Rukhsah).\n\n**Tawaf al-Wida (Farewell Tawaf)**\n\nThe last act before leaving Makkah. Perform 7 circuits around the Kaaba. Make du\'a and bid farewell to the Sacred Mosque with a heavy heart and tears of gratitude.\n\nMay Allah accept your Hajj and make it a Hajj Mabrur — a pilgrimage accepted by Allah.',
      arabic: 'أيام التشريق وطواف الوداع',
      sortOrder: 10,
    ),
  ];
}
